### ISSUE TITLE
Mark changes to third-party code base clearly

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#108]
It's good to make the changes to the thrid-party so clear that we can tell our changes to a file by just lookinf for the tag "CODINGSPECTATOR".

**Comment by reprogrammer** [comment]
I have marked our changes to the files in `org.eclipse.jdt.ui` except the following in d8573674fbf14d01d7835bcfdbcadcab2b82d736.
1. core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameLocalVariableProcessor.java
2. core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/RenameFieldProcessor.java
3. core refactoring/org/eclipse/jdt/internal/corext/refactoring/rename/JavaRenameProcessor.java
4. ui/org/eclipse/jdt/internal/ui/JavaPlugin.java
5. core refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/CompilationUnitReorgChange.java
6. core refactoring/org/eclipse/jdt/internal/corext/refactoring/changes/RenameCompilationUnitChange.java
7. ui refactoring/org/eclipse/jdt/internal/ui/refactoring/RefactoringExecutionHelper.java

I marked the changes that we made to all the files that we had changed in `org.eclipse.jdt.ui` in 3ff7893b2871d8b6e6a364f7f93b2c4ac3010b0f.

**Comment by vazexqi** [comment]
How do other projects do this? While it can be quite useful, I think this is a lot of _busy work_ that requires an unnecessarily high overhead for maintenance. 

From what I have seen, you would usually just generate a patch against a certain revision in the repository and that would be the list of changes that you have (sans the formatting changes)

I agree that we should mark what files we changed but the level that we are aiming for is too low level right now. Marking the header of the file might be sufficient. By marking it with CODINGSPECTATOR at the top, we should be able to do `git grep` to find all those files and then if we are interested we would do a full git diff on that file.

I suggest that we ask Jeff about this. Personally, I am not very motivated to maintain this manual list since it will definitely be outdated easily and would be confusing once it is. As you have seen we have already forgotten to do this several times.

**Comment by reprogrammer** [comment]
I added the change markers to `org.eclipse.ltk.core.refactoring` in a0973ade13a5b4ab1d32d861d8490dce7000a084.

**Comment by reprogrammer** [comment]
a9a71dd6196d0f8b35b3aa5676b9defc40015799 adds change markers to `org.eclipse.jdt.ui.tests.refactoring`.

**Comment by reprogrammer** [comment]
9cab6fe84968d7cb57fcb1f4fe43a53a86545e0b and ee7d14ee5dd09b3ee9720e7e25f43309b8d5a3c7 add change markers to `org.eclipse.compare` and `org.eclipse.ui.editors`, respectively.

**Comment by reprogrammer** [comment]
51f7873a7c3197484f7fc87bfb9ab01761d0b12f added change markers to `org.eclipse.ltk.ui.refactoring`.
