### ISSUE TITLE
Capture refactorings performed through the Quick Assist menu

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#109]
Some refactorings such as convert string to local variable, convert local variable to field, etc can be invoked through the Quick Assist dialog. Currently, this refactoring is not performed through the RefactoringWizard mechanism so we can't capture them.

**Comment by vazexqi** [comment]
The check for whether a quick assist is available is done through `org.eclipse.jdt.internal.ui.text.correction.QuickAssistProcessor`

It will call `checkInitialCondiitions` on a predefined list of refactorings to see which are available.

**Comment by reprogrammer** [comment]
Resolved in f2f052753a62d2928de092ab59b9fd9b7ca3fb3b.

**Comment by reprogrammer** [comment]
I've reopened this issue because CodingSpectator doesn't capture invocation of renames using the quick assist. For example, if you get a list of quick assist proposals on a field and select `rename in workspace`, CodingSpectator will log the rename refactoring but it won't set the `invoked-by-quickassist` attribute in the XML.

I resolved this issue in d192bc4e54ec7696e5a6ce8e7aa13509163e9732.
