### ISSUE TITLE
We are eagerly logging refactorings that could be performed

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#110]
How to reproduce:
1. Extract method
2. Give the new method a name of an existing method (same method signature)
3. Click OK. A refactoring is logged by this point.
4. The RefactoringWizard will tell you that there is an error in the second page.
5. Click Cancel. Another refactoring is logged by this point.

Now we have double logging of a refactoring that was not actually performed!

**Comment by reprogrammer** [comment]
See my proposal for fixing this issue in df832280343d547fca205165487b8aba05d7b243.

**Comment by reprogrammer** [comment]
In the message of the commit df832280343d547fca205165487b8aba05d7b243, I said the following.

> The problem with instrumenting RefactoringWizard.performFinish is that the refactoring status is not complete when we create the refactoring descriptor. Thus, we don't capture the warning/error messages.

However, I couldn't produce this problem. That is, every time I got an error page through the refactoring wizard, the logged refactoring descriptor contained the latest warning and error messages. Therefore, I'm going to close this issue.

This issue is critical because it reports wrong data. Therefore, I'm going to release a new version that fixes it.

**Comment by reprogrammer** [comment]
Incorporated the fix in version v1.0.0.201011161607.
