### ISSUE TITLE
Decipher the formatting used in the serialized XML files for refactorings

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#119]
Right now the way the data is stored in the XML file is kind of cryptic. We need to use the internal deserialization mechanisms in Eclipse to decipher those parameters.

**Comment by vazexqi** [comment]
This issue has been subsumed by issue #138.

**Comment by reprogrammer** [comment]
@vazexqi: I reopened this issue because it is not entirely resolved. The tests deserialize the history files into descriptor objects. But, the descriptors just keep maps from attributes to the string values. In other words the tests parse the XML files but not the values of the attributes. For example, the value of the attribute "input" in a descriptor is of the form `/src<edu.illinois.codingspectator{RenameCompilationUnitTestFile.java[RenameCompilationUnitTestFile`.

**Comment by reprogrammer** [comment]
Actually, I changed my mind and decided to leave this issue closed. Simply, it depends on how we are going to use the values stored in the attributes. We don't need to parse the values of the attributes for testing. But, we might need them for future data analysis. So, let's leave this issue closed until a need for it arises.

**Comment by vazexqi** [comment]
OK. When I created the original issue that was what I had in mind (that we are just trying to figure out who to match the two) and we have done that in #138.

What you are saying is that you want to figure out the convention that Eclipse uses for the handler to the object. I am going to change the title and description of this issue to make it more clear.

**Comment by vazexqi** [comment]
OK. Following your updated comment. I am going to leave this issue as-is first and not make any changes.
