### ISSUE TITLE
Get code snippet from surround text of an ASTNode

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#14]
We can then query the ASTNode to get its surrounding nodes and get the text representation i.e. the code snippet.

**Comment by reprogrammer** [comment]
We use a threshold to see how many parents to go up the AST. This issue is closed by 746fb83697dd30e95ba773cb4e1b2bcd60243417.

We use the following method call to get the selected text during a refactoring

```
fCUnit.getBuffer().getText(fSelectionStart, fSelectionLength)
```

We hope that getBuffer doesn't return null when we call it because usually the file is open while performing a refactoring. But, we should check that it works for refactorings such as rename. For example, we should check if the buffer is available when renaming a file in the package explorer.
