### ISSUE TITLE
Undo doesn't work in instances with CodingSpectator

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#171]
With the latest version of CodingSpectator (from Master), it seems that I cannot invoke undo on anything (can't undo a refactoring, can't undo a text change).

Balaji confirms that this problem:
1. does not happen with an older version of CodingSpectator 
1. does happen with the latest version of CodingSpectator from master on his Linux machine

**Comment by rajkuma1** [comment]
Undo operation is available on version 1.0.0.201102192319

**Comment by Wanderer777** [comment]
If you are starting CodingSpectator from its source code (rather than installing the feature), please make sure that you close project `edu.illinois.codingspectator.codingtracker.replaying`. This project does not make part of the feature and would not be installed on a user machine. 

You need to make sure that this project is closed, because if it is not, then the editor's behavior would be slightly altered, including the inability to perform an undo. This altering was necessary for the replaying phase, because otherwise if a refactoring that affects several files is undone/redone, it will pop up a confirmation dialog box, which would disrupt the replaying process.

**Comment by reprogrammer** [comment]
I could not reproduce this problem on my Ubuntu laptop. I successfully invoked the undo operations on my textual edits and refactorings. I use Eclipse Helios SR1 with HEAD pointing to c87e36e9de3afe0681a65ef0d9c574d04322c994. Note that I ran CodingSpectator in DEBUG_MODE and TESTING_MODE and saw CondingTracker capturing the undo operation.

**Comment by vazexqi** [comment]
I see. I will close edu.illinois.codingspectator.codingtracker.replaying from my workspace then.
