### ISSUE TITLE
Too long paths in edu.illinois.codingspectator.ui.tests

### ISSUE THREAD

**Issue by Wanderer777** [vazexqi/CodingSpectator#180]
File paths in plugin `edu.illinois.codingspectator.ui.tests` are too long for Windows OS (the limit on Windows is 256 characters). As a result, it is not possible to completely pull (and correspondigly, commit/push) CodingSpectator on a Windows machine.

**Comment by vazexqi** [comment]
I have the same problem on Windows 7 so I am guessing the 255 characters is still there. This is what happens when I do a clean checkout:

<pre>
$ git clone git@github.com:vazexqi/CodingSpectator.git
Cloning into CodingSpectator...
remote: Counting objects: 37341, done.
remote: Compressing objects: 100% (20201/20201), done.
remote: Total 37341 (delta 13625), reused 36899 (delta 13444)
Receiving objects: 100% (37341/37341), 14.32 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (13625/13625), done.
fatal: cannot create directory at 'edu.illinois.codingspectator.ui.tests/expected-refactoring-descriptors/extract-constant/CancelledExtractConstantTest/TestProject_class edu.illinois.codingspectator.ui.tests.extractconstant.CancelledExtract
ConstantTest': No such file or directory
</pre>

**Comment by vazexqi** [comment]
Also see http://stackoverflow.com/questions/4992577/msys-git-and-long-paths

**Comment by reprogrammer** [comment]
I will shorten the length of the path by using the simple name of the test class as the project name.

**Comment by reprogrammer** [comment]
2319710f2b6e903c0362691c722c4988476afee3 shows how to make the longest path of the repository fit in 242 characters.

**Comment by vazexqi** [comment]
See my comment on that commit.

**Comment by reprogrammer** [comment]
Updated the names of test projects in the following commits.
- extract constant: 2c16fe87346f21edee46b7fe454979ec7e06ea24
- extract interface: 29eedebe82e7b8d20e5321e287491ba3959a5054
- extract method: a17df03817d4ed09c6975b01bfbd8fb71ec06ec1
- extract superclass: 49cd1992275cf362800e68cfa8c227368a831ae1
- inline: 7a982739117d237eddb17fc5e60eaafed7a4797e
- move: a954c4a2d0091980408aceda5744895a29de5bf7
- push down: ad9409ec17c86e4c32632452a01e26afc3e66900
- rename: 76b41ac26c1ee4f29721c8938b36c735d9858ce8

**Comment by reprogrammer** [comment]
Nick, Stas and I realized today that it's not sufficient to shorten the paths in the heads of the branches. We also need to remove the long paths from the history of the git repository.

**Comment by reprogrammer** [comment]
It took me about three hours to shorten the length of paths in `edu.illinois.codingspectator.ui.tests` because I needed to both update the folders and the project names in expected refactoring descriptors.

To save some time, I will write a script to further shorten the names of the tests.

**Comment by reprogrammer** [comment]
I wrote up a script to shorten the path lengths and made it available at https://gist.github.com/883264.

**Update:** Added the script to "coding-convention/scripts" in ba771da71a7c364c6fbb217a14e1ea116edfe990.

**Comment by Wanderer777** [comment]
I do not know Ruby, so I can not tell about the details, but overall the script looks good to me. I have just 2 comments:
- I think that the paths produced by the script would fit into 200 characters (or less) limit, though there is still some room for reducing the paths, e.g. expected-descriptors and performed|eclipse could be shortened as well. At the same time, that might impact the readability of the tests, so maybe we should not do that.
- If new tests are added (after the script shortened the paths), values for Tdd and Pddd would be created manually, which should be done in a consistent manner. Would it be easy to figure out the right values for a new test just looking on the existing tests?

**Comment by vazexqi** [comment]
I think we can leave expected-descriptors and performed | eclipse alone. Those are quite short already and won't grow longer as we add more tests (constant length). I think Txx/Pxxx i.e. 2-digits and 3-digits should be sufficient.

I also have the same concern like Stas, where do we do the mapping from Java tests to the actual tests? It's probably going to be a comment file somewhere.

**Comment by vazexqi** [comment]
In reply to https://github.com/vazexqi/CodingSpectator/issues#issue/180/comment/906245

I tried something today:

<pre>
# I'm in the C:\g directory and cloning into CS
nchen@ISRAFEL /c/g
$ git clone -b verify-captured-log git@github.com:vazexqi/CodingSpectator.git C
S
Cloning into CS...
remote: Counting objects: 37920, done.
remote: Compressing objects: 100% (20359/20359), done.
remote: Total 37920 (delta 13792), reused 37599 (delta 13632)
Receiving objects: 100% (37920/37920), 14.36 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (13792/13792), done.
</pre>


This shows that `git clone` can successfully clone the tip of the repository (the one that does not have the long file names). Also notice that I am cloning into C:\g\CS so that it does use up all 255 characters. We don't need to rewrite history or clean up the index.

This implies that once we shorten the paths and commit, Stas should be able to clone without our needing to do the patch+rebase magic that we discussed.

The only downside is that Stas (or any other Windows user) cannot revert/check-out an earlier version of the history. However, this use case is very unlikely so we don't need to worry about it.

**Summary**: once we shorten the paths, Stas should be able to pull. He can actually pull now as well as long as he clones into something short like C:\CS

**Comment by reprogrammer** [comment]
I shortened the paths even further in cffdea2644e3e6e7d999e68a48a2b8e1255c10e6.

**Comment by reprogrammer** [comment]
28d91b90516bb748777ec5c0f5ea5fee4608d68d renamed all the remaining tests to Tdd.

**Comment by reprogrammer** [comment]
66bd19d909e7ec6f1290bd9f66d7561049965b06 merged branch `verify-capture-log` with short paths into `coding-tracker` so that Stas can resume working on `coding-tracker`.

**Comment by reprogrammer** [comment]
See "edu.illinois.codingspectator.ui.tests/README" for the mapping between the old and new names of the tests.
