### ISSUE TITLE
Limit the length of paths

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#182]
We need to enforce a limit on the maximum possible length of paths (e.g. 200 characters) in our git repository to avoid issue #180 in future.

We've enforced rules for the format of commit messages in the past (see [commit-msg](https://github.com/vazexqi/CodingSpectator/blob/master/coding-conventions/commit-msg)). We should look for ways to make git automatically check the length of paths and reject commits that contain long paths.

**Comment by vazexqi** [comment]
If you look at your .git/hooks folder for any repository there is a pre-commit.sample file. This sample checks to see that the files to be committed don't have non-ASCII characters. We can use this as a starting point for our own check to ensure that file names are not longer than 200 characters.

I think it would also be nice to have the check for non-ASCII characters since potentially that could cause other issues.

**Comment by vazexqi** [comment]
Take a look at https://gist.github.com/882693

(I did not check it in yet because I want to make sure that this works on Windows and also because we are in the stage of trying to fix something in our repository so we should not add unnecessary commits at this point)

Unfortunately, there is no hook for adding files to git; thus I can't prevent you from adding a file to the index. However, when you attempt to commit then you will have a warning.

Here is how to resolve that warning:

<pre>
$ git commit # Will fail the check
Error: Attempting to commit a file that is longer than 200 characters.

Loremipsumdolorsitamet,consecteturadipiscingelit.Sedaliquam,felisaccondimentumpretium,turpisnuncsemperturpis,egetconguearcuduisitametturpis.Mauristempusbibendumlacusutsollicitudin.Aliquameratvolutpat.Innuncmimetus
has 213 characters.

$ git reset HEAD Loremipsumdolorsitamet,consecteturadipiscingelit.Sedaliquam,felisaccondimentumpretium,turpisnuncsemperturpis,egetconguearcuduisitametturpis.Mauristempusbibendumlacusutsollicitudin.Aliquameratvolutpat.Innuncmimetus

$ mv Loremipsumdolorsitamet,consecteturadipiscingelit.Sedaliquam,felisaccondimentumpretium,turpisnuncsemperturpis,egetconguearcuduisitametturpis.Mauristempusbibendumlacusutsollicitudin.Aliquameratvolutpat.Innuncmimetus shortName

$ git add shortName

$ git commit #Will pass the check

</pre>

**Comment by reprogrammer** [comment]
@vazexqi,

Can you please commit the script at https://gist.github.com/882693 into the "coding-conventions" folder and update the [Contributing to CodingSpectator wiki page](https://github.com/vazexqi/CodingSpectator/wiki/Contributing-to-CodingSpectator) with instructions on how to install the script?

**Comment by vazexqi** [comment]
Committed in c04d4d64103395f25336dc425dfa53a6828b1c39

I am not sure of the original license since it was part of the default git distribution. So I did not leave a license header.

**Comment by reprogrammer** [comment]
[According to Wikipedia](http://en.wikipedia.org/wiki/Git_software), Git is released under GPL.

**Comment by vazexqi** [comment]
So what do you want to do? Make that portion follow GPLv2? Or just re-write it from scratch so that we have a license compatible with Illinois/NCSA? If we re-write it from scratch it will probably not have the non-ASCII checks since I did not write that part.

**Comment by reprogrammer** [comment]
CodingSpectator doesn't use this script. So, it's safe to leave this script under GPLv2. However, I'm not sure if that script is indeed release under GPLv2 since it doesn't come with a license header.

**Comment by reprogrammer** [comment]
@vazexqi: I replaced "pre-msg" by "pre-commit" on [the wiki page](https://github.com/vazexqi/CodingSpectator/wiki/Contributing-to-CodingSpectator). Do you agree with this change?

**Comment by vazexqi** [comment]
Yes. It was a typo.

**Comment by reprogrammer** [comment]
Made the `pre-commit` script executable in 94d97f0c6b5149b555bcd6b7700575a9f7c8f642.

**Comment by vazexqi** [comment]
b0580a46684a0ac3abf342fe20fc7aba95d63f68 fixes an issue where the script melds together multiple file names.
