### ISSUE TITLE
Capture the compilation problems generated by a refactoring

### ISSUE THREAD

**Issue by rajkuma1** [vazexqi/CodingSpectator#191]
Consider the move refactoring on the code snippet below:

```
public class C {
    int i;
    void m() {
        System.out.println(i + i);
    }
}

class C2 {

}
```

Moving the variable `i` from class `C` to `C2` would not give any warnings to the user. However, once the refactoring is performed, a compilation error is observed.
CodingSpectator does not know of this error since the refactoring does not report any warning or error messages.

Capturing this error information from the `Problems` view could be helpful.

**Comment by rajkuma1** [comment]
The `Problems` view gets updated when the performed refactoring breaks the code. And, we are interested in capturing the compilation problems due to refactorings. We'd like to begin listening to the problems when a refactoring is about to get performed and stop listening to it when the refactoring is done.

**Comment by reprogrammer** [comment]
@Wanderer777: I think CodingTracker captures the event when a refactoring is about to be performed. We're interested in getting notified about this and start listening to the `Problems` view. Does CodingTracker capture such events? Can you give us some hints on how to get notified when a refactoring is about to be performed?

**Comment by Wanderer777** [comment]
Yes, CodingTracker captures events that tell that a refactoring is about to be performed and that it was performed. Implementation of method _executionNotification(RefactoringExecutionEvent)_ in class _RefactoringExecutionListener_ shows how it is done. 

Please note that replaying some recorded user operations, I discovered an instance, where the notification that a refactoring is about to be performed was received, but the corresponding notification that this refactoring was performed was not received. So, capturing every update to the `Problems` view in between these notifications could be misleading in such scenario. To address this problem, you can look for the first update to the `Problems` view in between these notifications. This should work except in a scenario, when a refactoring's second notification (is performed) is not recevied, and the refactoring did not update the `Problems` view.

**Comment by vazexqi** [comment]
@Wanderer777: Do you know if there is a proper API to query the Problems View (or Model) for information? I am asking because it is possible for the user to [filter](http://tech.rickumali.com/blog/2010/01/30/filtering-problems-view-eclipse) the Problems View to a specific project, working set, severity, etc. I do this as well for bigger projects.

So if we are not careful when we query for it (like maybe asking the list what it is displaying right now), we might actually miss problems that are not being displayed but are in the database.

By the way, this method of capturing the problems view is also grounded on the assumption that the user has turned on "Build Automatically". If that option is not turned on, we might not gather anything. It is unusual for "Build Automatically" to be turned off but I have sometimes accidentally turned it off and didn't turn it back until later.

**Comment by Wanderer777** [comment]
No, I do not know API to query the Problems View. But considering the scneario that you desribed above, where the user can configure the Problems View such that it does not display all the information, I think that it would be better to listen not to the Problems View but to the same source the Problems View is listening to. 

As about turning off "Build Automatically", I wonder if we can simulate it being always on for the affected files, i.e. trying to build the files changed by a refactoring and catch all compilation problems that appeared after the refactoring. But we need to do this in a non-intrusive way, such that if "Build Automatically" is off, the user does not see that we build those files for our purposes (i.e. we should not produce .class files on the disk, our build is stored in the memory).

**Comment by vazexqi** [comment]
Problems annotations are a form of resource markers in Eclipse. As such, it might be possible to use the `ResourceChangeEvent` to monitor for changes to the workspace. There are two possible ways to do this:
1. Try to hook into [`ResourceChangEvent#findMarkerDeltas()`](http://help.eclipse.org/helios/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/resources/IResourceChangeEvent.html#findMarkerDeltas%28java.lang.String, boolean%29). Though we might not have control over when the events are sent and we would like to be notified just as the refactoring is performed and just after.
2. Writer our own traversal through the workspace to get a snapshot of all the problem markers on all the resources **before** the refactoring and **after** the refactoring. This entails doing a _set difference_ between the problem markers before and after the refactoring. Finding the markers can be done using [`IResource#findMarkers`](http://help.eclipse.org/helios/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/resources/IResource.html#findMarker%28long%29). Getting the workspace can be done using [`ResourcePlugin`](http://help.eclipse.org/helios/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/resources/ResourcesPlugin.html)

For both methods, we have to be careful as well since we don't know _when_ (immediately? a few seconds?) after the refactoring so that we can capture compilation errors.

**Comment by vazexqi** [comment]
c1581f4c033810efdad8af97108ee24e71011ce5 is an initial attempt at capturing the problems using [`IResourceChangeEvent#findMarkerDeltas()`](http://help.eclipse.org/helios/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/resources/IResourceChangeEvent.html).

The committed files contain TODO's on how to proceed next.

**Comment by vazexqi** [comment]
BTW, Balaji had a good example of when it was necessary to turn off build automatically. This was with the Metrics plug-in for Eclipse. It was piggy-backing on the incremental build and trying to calculate the metrics. However its calculation of metrics was extremely slow and bogged down editing. So in that case, "Build Automatically" had to be turned off.

**Comment by vazexqi** [comment]
@Wanderer777, @reprogrammer: Do you have an example of a refactoring that trigger ABOUT_TO_PERFORM but not PERFORMED? Is this one of the cases where the refactoring is buggy and does not make it through? I want to get a sense of how prevalent this case is and whether we need to take care of it.

**Comment by Wanderer777** [comment]
I investigated the instance of a refactoring for which only ABOUT_TO_PERFORM was recorded. Unfortunately, neither Eclipse log, nor CodingSpectator captured anything about it (and CodingTracker just registered the event, at this point the descriptor is not recorded). So, I do not know what kind of refactoring was that and how it failed. Considering that this is the only obeserved case so far, I do not think that this happens too often.

**Comment by vazexqi** [comment]
4e51e474bd9a9d5c2f9ee79c32fed61285b0a0b3 shows how to use XMLEncoder to serialize the info. 

The output is a bit too verbose: https://gist.github.com/906173

We might be better off using a different XMLWriter. Perhaps the internal one available through Eclipse (org.eclipse.core.internal.resources.XMLWriter)

**Comment by reprogrammer** [comment]
Computed the compilation problems before and after refactorings in 5967c9692e3e6e7add54e341bdcb82a91a302a33 and 56564f204a00a3847f43d4d2af815953ae6cf4c7.

**Comment by vazexqi** [comment]
**CompilationUnit does not exist**

Problem: When a refactoring affects multiple files and one (or more) of those files is not open in a visible editor, we will get the following exception with `ReconcileWorkingCopy`

<pre>
Java Model Exception: Java Model Status [[Working copy] C2.java [in <default> [in src [in P]]] does not exist]
    at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:784)
    at edu.illinois.codingspectator.refactoringproblems.logger.ProblemsFinder.computeProblems(ProblemsFinder.java:52)
    at edu.illinois.codingspectator.refactoringproblems.logger.ProblemsFinder.computeProblems(ProblemsFinder.java:65)
    at edu.illinois.codingspectator.refactoringproblems.logger.RefactoringProblemsListener.storeCurrentProblems(RefactoringProblemsListener.java:73)
    at edu.illinois.codingspectator.refactoringproblems.logger.RefactoringProblemsListener.historyNotification(RefactoringProblemsListener.java:65)
    at org.eclipse.core.commands.operations.DefaultOperationHistory$2.run(DefaultOperationHistory.java:939)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.commands.operations.DefaultOperationHistory.notifyListeners(DefaultOperationHistory.java:928)
    at org.eclipse.core.commands.operations.DefaultOperationHistory.notifyAboutToExecute(DefaultOperationHistory.java:951)
    at org.eclipse.core.commands.operations.DefaultOperationHistory.openOperation(DefaultOperationHistory.java:1333)
    at org.eclipse.ltk.internal.core.refactoring.UndoManager2.aboutToPerformChange(UndoManager2.java:139)
    at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:254)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1975)
    at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:306)
    at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:92)
    at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:218)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1975)
    at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:87)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
</pre>


Solution: 

<pre>
    private void openAffectedCompilationUnits() throws JavaModelException {
        for (CompilationUnit cu : affectedCompilationUnits) {
            cu.becomeWorkingCopy(new NullProgressMonitor());
        }
    }
</pre>


This has not visible UI effects.

**Comment by vazexqi** [comment]
f68604b3e22b5fb8ce1d45e8d1e11889fc895db4 tries to compare the set of problems before and after a refactoring has been performed.

**Comment by reprogrammer** [comment]
Merged branch `log-refactoring-problems` into `master`.
