### ISSUE TITLE
Selection information captured through quick-assist is wrong

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#195]
```
class C1 {
    public static void main(String[] args) {
        int i = 0;
        System.out.println(i);
    }
}
```

Move the cursor to the position just before variable 'i' in the System.out.println line. Eclipse captures the following information erroneously (all are related to one another):
1. selection-text (i=0 but should be the empty string since nothing was selected by the user)
2. selection (would capture the position of i=0)
3. selection-in-code-snippet (would capture the position of i=0 in the code snippet)

**Comment by vazexqi** [comment]
This is probably because of how the QuickAssist processes the reference. We suspect that when we invoke it, it tries to resolve the binding for the variable and passes that instead to InlineTempRefactoring. Either variable (i=0 or i in the System.out.println) is a valid argument to the InlineTempRefactoring so it would work. But the selection does not faithfully reflect what the user has selected.

**Comment by reprogrammer** [comment]
Eclipse doesn't capture the selection information correctly as reported in [a comment](https://github.com/vazexqi/CodingSpectator/issues/146#issuecomment-1096456) of issue #146 . However, CodingSpectator now captures the selection information correctly perhaps since we switched to ITypeRoot from the global store (see issue #220).
