### ISSUE TITLE
CodingSpectator does not capture compilation problems due to failed refactorings

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#200]
Sometimes, Eclipse makes a notification for a refactoring that is about to be performed, undone or redone. CodingSpectator takes a snapshot of the current compilation problems when it receives this notification. Then, when the refactoring finishes, CodingSpectator takes another snapshot, computes the differences between the two snapshots and logs the differences. The problem is that if the refactoring fails, CodingSpectator doesn't compute a snapshot of the compilation problems after the failure of the refactoring. Thus, CodingSpectator misses any changes to the compilation problems due to a failed refactoring. CodingSpectator could listen to failures of refactorings using `org.eclipse.core.commands.operations.OperationHistoryEvent.OPERATION_NOT_OK` of `org.eclipse.core.commands.operations.IOperationHistoryListener`.

**Comment by rajkuma1** [comment]
`edu.illinois.codingspectator.refactoringproblems.logger.RefactoringProblemsListener` listens to operation history events.
Need to update `edu.illinois.codingspectator.refactoringproblems.logger.RefactoringProblemsListener.historyNotification(OperationHistoryEvent)` for a check for `org.eclipse.core.commands.operations.OperationHistoryEvent.OPERATION_NOT_OK`.
But, I need to be sure that this in fact kicks in when there are failures in refactorings.

**Comment by rajkuma1** [comment]
While trying to work an example for this case, I stumbled across this. This is an issue with both coding spectator and eclipse. Please take a look at this.
https://github.com/vazexqi/CodingSpectator/issues/146#issuecomment-1048273

**Comment by rajkuma1** [comment]
@reprogrammer
@vazexqi
Do either of you know of a test that should trigger operation history callback with event `org.eclipse.core.commands.operations.OperationHistoryEvent.OPERATION_NOT_OK` ?

**Comment by reprogrammer** [comment]
@rajkuma1: Try stopping the refactoring while it's still in progress to see if Eclipse sends the `OPERATION_NOT_OK` event. Usually, when you invoke a refactoring, a progress bar pop shows up while the refactoring is being performed. I think if you terminate the refactoring before it's finished, Eclipse sends the `OPERATION_NOT_OK` event.

@Wanderer777: Please let us know of some other ways to make Eclipse send the `OPERATION_NOT_OK` event.

**Comment by rajkuma1** [comment]
ok. Got it.
Here are the steps:
1. Create a project, say, `P1`.
2. Create a class in the project, say, `C`.
3. Create another project, say `P2`.
4. Perform a `move refactoring` of `Class C` from `P1` to `P2`.
5. Delete `P2`.
6. Go to the project explorer view and start undoing.
7. First the project `P2` will appear.
8. The next undo will fail. That's the case we're looking for.

**Comment by Wanderer777** [comment]
Refactoring changes are usually executed quite fast. Therefore, instead of trying to cancel them in the middle of the execution, I used the following approach to get the `OPERATION_NOT_OK` event. I put a breakpoint at the point when a change is about to be executed (after all preconditions are checked and pre-execution notifications sent out). Then, I do something externally that would make the change fail (e.g. if the change is moving a file, I rename or delete this file). Then, I resume execution and get the `OPERATION_NOT_OK` notification.

**Comment by rajkuma1** [comment]
Added 31eebeeb2ad8daf623c9f5329c833c2e07e9cbc6 .. 6c7000a5d5d93665bcb53a5f55f4a6a82149e738 to capture the snapshot of the compilation problems when `OPERATION_NOT_OK` event occurs.

The affected compilation units is an empty set since the `org.eclipse.ltk.internal.core.refactoring.UndoableOperation2ChangeAdapter.fActiveChange` is null. The undo history is cleared once such an event is generated.
I'm not sure why we need to capture the snapshot of compilation unit errors for this scenario.

Instead, logging details about the operation that failed would be useful.

`org.eclipse.core.commands.operations.OperationHistoryEvent` contains useful information about the undo operation that just failed:
`org.eclipse.core.commands.operations.OperationHistoryEvent.status` : Status ERROR: org.eclipse.ltk.core.refactoring code=4 'P3/src/C10.java' does not exist anymore. null

`org.eclipse.core.commands.operations.OperationHistoryEvent.operation` : contains the operation that just failed.

By collecting this information, we can arrive at numbers based on reasons for failures in refactorings.

One thing that could be done is to inform the user that further undo operations would not be possible.
This would improve the IDE experience.

**Comment by reprogrammer** [comment]
@rajkuma1:

I've got a few comments.
1. CodingSpectator does not compute the set of affected compilation units when it receives the `OPERATION_NOT_OK` event. Rather, it computes and saves the affected compilation units when the refactoring is about to be performed. Then, it uses the saved list of compilation units later when the refactoring finishes successfully or unsuccessfully.
2. You mentioned undo operations and undo history in your comment several times. What is special about undo operations? How do they relate to refactorings?
3. I like the idea of capturing more information about failures of refactorings. But, we have to do a cost & benefit analysis and discuss the architectural issues.

**Comment by reprogrammer** [comment]
@Wanderer777: How can we check if an event received in `RefactoringProblemListener` is a refactoring event?

**Comment by Wanderer777** [comment]
`RefactoringHistoryService` listens to `OperationHistoryEvent` events in a way similar to `RefactoringProblemListener`, so you can see how it is done there, in particular take a look at methods `performHistoryNotification` and `getRefactoringDescriptor` in class `RefactoringHistoryService`.
