### ISSUE TITLE
CodingSpectator doesn't always capture UDC data

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#214]
CodingSpectator doesn't capture UDC data from all of our participant. Our hypothesis was that CodingSpectator doesn't set the preference store at `.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.epp.usagedata.gathering.prefs`. But, we found that CodingSpectator sets this preference in `org.eclipse.epp.usagedata.internal.gathering.Startup.earlyStartup()`. We tried to reproduce the problem on our machine. We got a fresh instance of Eclipse and disabled the option for capturing UDC data on the preference page for "Usage Data Collector". Then, we installed CodingSpectator. Sometimes, UDC captures data after CodingSpectator is installed but sometimes it doesn't. At this point, we don't know how to deterministically reproduce the problem.

**Comment by vazexqi** [comment]
We will have to examine the workspace of those participants directly to see if we have missed something.

**Comment by vazexqi** [comment]
It seems that that particular participant had downloaded the SDK version of Eclipse from http://download.eclipse.org/eclipse/downloads/drops/R-3.6.2-201102101200/index.php

This configuration of Eclipse does not seem to include the UDC component by default – this is very weird since UDC seems to be an integral feature of the runtime. This explains why we weren't getting data from this participant for UDC.

I'm pushing this bug to the next version since it would take some time to figure out what we can do when UDC is not included by default. Additionally, it is also very unlikely that most developers would use the SDK version of Eclipse – the download link is not featured on the main page – so this problem will not affect most people.

N.B. We looked only at the participants using Helios. Other participants using Indigo also do not have UDC data.
