### ISSUE TITLE
Instrument Pull Up Refactoring

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#22]
The Pull Up Refactoring is worth investigating because its structure is different from the other two refactorings that we have seen: Extract Method and Inline Method.

Pull Up Refactoring is a _ProcessorBasedRefactoring_ instead of a regular _Refactoring_ instance. Ideally it will allow other _participants_ to hook into the refactoring process. However, from examining the code, this decision might have been an overengineering decision since there are currently no participants yet.

More importantly, this Pull Up Refactoring is different from other refactorings because it it is based on selecting elements instead of text in the editor.

I suspect that all refactorings in the package org.eclipse.jdt.internal.corext.refactoring.structure are of this genre.

So currently there are two classes of refactorings: text-selection and element-selection (through some wizard).

**Comment by reprogrammer** [comment]
Partially resolved in 9cf47981ca9150bba1ded2a97af9398a1b17bc7c .. f669b95a858be6e3ae3fe308ba927dae356a4dcf.

**Comment by reprogrammer** [comment]
The Pull Up Refactoring has some problems when the same method is defined in both the parent class and the child class. Here is an example:

```
class Parent {
  public void m() {}
}

class Child extends Parent {
  public void m() {}
}
```

If the user selects the method `m()` in the child class and tries to pull it up, Eclipse throws an exception (no warnings). If the user invokes the refactoring by the button sequence "FINISH, OK" (and not "NEXT", "NEXT", "CANCEL"), CodingSpectator will suffer from the following problems:
1. We cannot correctly capture this behavior using our current mechanism and we will erroneously double-count this as a performed refactoring.
2. We capture this unfinished refactoring as a performed and we report the status as "OK" even though an exception has occurred.
3. Eclipse itself does not capture this as a performed refactoring since it listens for `createChange()` so we have mismatch with what is reported in the Refactoring History list.
4. The navigation history won't record hitting the "OK" button of the error dialog.

In bc66aebc1d2104d7856d41143cd331ee819c2abc, we changed the test for the above invalid pull refactoring such that it prints a message to the console reminding us the problem in capturing the refactoring.

The error dialog the the pull up refactoring shows in the above case is opened by the `handle` methods of `ExceptionHandler`. But, it's difficult to record the message shown by `ExcpetionHandler` because we don't necessarily have access to the descriptor when `ExceptionHandler` comes into play.

**Comment by reprogrammer** [comment]
Clarified the error message for [the problem reported above](https://github.com/vazexqi/CodingSpectator/issues#issue/22/comment/729938) in 012f5bfa04bd8f8c59310cc1ad0b292ce4922d27.

**Comment by reprogrammer** [comment]
We capture the error log (issue #143) to be able to identify such internal problems of the refactoring tools. Unfortunately, we cannot easily capture the error message or the timestamp of pressing the "OK" button on the error dialog. Therefore, we are closing this issue.

**Comment by reprogrammer** [comment]
Commit 3daf88563cf5ae2d91dce7dbcc65e6fc31401067 fixes the exceptions thrown in pullup.(T01,T02).
