### ISSUE TITLE
Some timestamps are -1

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#237]
@Wanderer777 reported the following problem:

> It looks that there appeared a problem with timestamps in refactoring descriptors. In CodingSpectator of May 17th it works good:  method RefactoringDescriptor#getTimeStamp() returns the correct timestamp for a refactoring that is about to be performed (please see RefactoringExecutionListener#executionNotification -> OperationRecorder#recordStartedRefactoring -> new NewStartedRefactoringOperation(..) ).
> 
> At the same time, in CodingSpectator of May 24th the same method call of RefactoringDescriptor#getTimeStamp() returns -1. So there might be something related to RefactoringDescriptor creation that has changed since May 17th and broke the original behavior. Please confirm. This problem is severe enough to be part of the release scheduled for today.

**Comment by reprogrammer** [comment]
@Wanderer777: The only commit that I think might be related to this problem is dc2d90248d6850f2d10fd3546edd6c9f3906dba8. This commit is related to issue #120. As part of this commit, [I reverted our change to `RefactoringDescriptor`](https://github.com/vazexqi/CodingSpectator/commit/dc2d90248d6850f2d10fd3546edd6c9f3906dba8#diff-5). That is, the original version of RefactoringDescriptor from Eclipse Helios didn't initialize the timestamp in the constructor of `RefactoringDescriptor`. Could you verify whether the problem you've discovered is due to this commit or not? If this commit breaks CodingTracker it probably means that CodingTracker had relied on a timestamp that wasn't set in the original version of Eclipse Helios. If this is the case, we need to discuss ways to fix the problem by considering both CodingTracker and CodingSpectator.

**Comment by Wanderer777** [comment]
@reprogrammer: Yes, I think that CodingTracker had relied on the CodingSpectator's code that set the timestamp in constructor of `RefactoringDescriptor`. As of now (presumably, the default Eclipse Helios behavior), the timestamp of a refactoring descriptor is set only after the refactoring is DONE (see `RefactoringHistoryService#performHistoryNotification`), therefore it is not available when a refactoring is about to be performed. 

An easy fix would be to take the current system's time instead of the refactoring descriptor's timestamp for the CodingTracker's record. But considering that sometimes we need to match timestamps of CodingTracker and CodingSpectator, it would be better if we could use the same timestamp for both of them. Any ideas on how to do that?

**Comment by reprogrammer** [comment]
@Wanderer777: I would rather match timestamps when we analyze the data than hack the way Eclipse assigns the timestamps and make the timestamps of CodingTracker and CodingSpectator exactly the same. I think it's safer to minimize our changes to the timestamp assigments of Eclipse. I assume your easy fix will not alter the timestamp of the refactoring descriptors and it'll just set the timestamps of the events that CodingTracker captures, right?

**Comment by Wanderer777** [comment]
@reprogrammer: Yes, CodingTracker would use the current system time while recording a refactoring that is about to be performed (for refactorings that are undone or redone, the timestamp is set correctly). But it would be implemented in the following way: if a refactoring descriptor's timestamp is not set (i.e. it is -1), CodingTracker will take the current system time. Otherwise, it will take the timestamp from the refactoring descriptor (this would allow easier tracking of undone and redone refactorings).

**Comment by reprogrammer** [comment]
@Wanderer777: Sounds good. Please update this issue when you have a fix for it.
