### ISSUE TITLE
Explain the difference between UDC and CodingSpectator on FAQ

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#250]
Some of the people I've invited to participate in CodingSpectator have asked me about the need to do a research study such as CodingSpectator given that Eclipse already collects usage data via UDC. Therefore, I suggest to add the following question and answer to the FAQ page.

**Eclipse already collects some usage data from its users. Have you considered analyzing the data collected by UDC?**

The [Eclipse usage data collector (UDC)](http://www.eclipse.org/epp/usagedata/) is installed by default on most Eclipse installations. And, [the Eclipse foundation publishes the captured UDC data regularly](http://www.eclipse.org/org/usagedata/results.php). But, we would like to study the use of certain tools in [Eclipse JDT](http://www.eclipse.org/jdt/). And, UDC does not collect the data we need to reach our goals. So, we have developed our own Eclipse bundle to capture the data we need to answer our questions about the usage of certain tools in Eclipse.

**Comment by vazexqi** [comment]
I am getting a sense of deja vu that we had this discussion before. I remember that I wanted to mention UDC somewhere (in the invitation e-mail or the description) so that we can contrast our work with UDC but you wanted us not to mention it because you said it might be confusing.

I'll add it to the FAQ because I agree that we need to differentiate ourselves.

**Comment by vazexqi** [comment]
Addressed at http://codingspectator.cs.illinois.edu/FAQ
