### ISSUE TITLE
Update the instructions to install CodingSpectator

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#255]
I've added CodingSpectator to Eclipse market place (See http://marketplace.eclipse.org/content/codingspectator-eclipse-helios and http://marketplace.eclipse.org/content/codingspectator-eclipse-indigo). So, CodingSpectator can now be installed without the need to have the URL of the update site. It would be nice to update the user guide to describe this method of installing CodingSpectator.

**Comment by vazexqi** [comment]
What are the advantages/disadvantages of installing from Market Place? I've never used it before. Can it be updated through the same mechanism?

**Comment by reprogrammer** [comment]
The advantage of installing a plug-in from the Eclipse Marketplace is that the user doesn't need to know the URL of the update site. For example, if the user wants to installing CodingSpectator. He/She could just go to `Help -> Eclipse Marketplace...` and search for the name "CodingSpectator" to install the plug-in. You can think of the Eclipse Marketplace as an app store for Eclipse. It doesn't matter if the user installs the plug-in via the Marketplace or by using the update site URL. In either case, the user will be able to update because the installation mechanisms are the same. The difference is just in initiating the installation: by name or URL.

The disadvantage of the Eclipse Marketplace is the poor search feature of its client (See [the related stackoverflow question](http://stackoverflow.com/q/6438713/130224) for more details).

**Comment by vazexqi** [comment]
I was trying to check whether we can legally post our plug-in to the marketplace (since, technically, our plug-in is not really a product that enhances Eclipse but more of a user study tool). It seems that the marketplace is moderated so if the moderator approved your post we should be fine.

Should we just stick with one way of installing? I don't see the benefit of mentioning both ways to install since it only serves to confuse the user and make the user guide longer than necessary. Since the only way to use Marketplace is through the _broken_ search feature, that makes it less attractive as an option.

**Comment by reprogrammer** [comment]
The broken search feature of the Eclipse Marketplace client makes this method of installation less attractive. Let's stick with the current method of installation, i.e. using the update site URL.

**Comment by reprogrammer** [comment]
By the way, I reported this [issue](http://www.eclipse.org/forums/index.php/mv/msg/214994/687559/#msg_687559) on the Eclipse forum for Equinox. But, as of 7/2/2011, no one has responded to my post.

**Comment by reprogrammer** [comment]
I opened [Eclipse Bug 351493](https://bugs.eclipse.org/bugs/show_bug.cgi?id=351493) for this issue.
