### ISSUE TITLE
Simplify the API of CodingTracker for refactoring events

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#300]
CodingTracker deserializes the refacoring events in the old format of the CodingTracker logs into the subclasses of `RefactoringOperation`, and deserializes the refactoring events of the new format of CodingTracker logs into `NewStartedRefactoringOperation`/`FinishedRefactoringOperation`.

It would be nice to provide a single interface for refactoring events to the clients of CodingTracker. A single interface for the refactoring events of CodingTracker will free the clients of CodingTracker from worrying about the differences in the old and new formats of CodingTracker logs.

**Comment by Wanderer777** [comment]
@reprogrammer: Although the content and most of the functionality of the subclasses of `RefactoringOperation` and `NewStartedRefactoringOperation` are the same, there is one significant difference: refactorings recorded as subclasses of `RefactoringOperation` have to be replayed because at that point we did not record all lower level changes produced by refactorings (which could be replayed instead of the refactoring), while refactorings recorded as `NewStartedRefactoringOperation` are replayed only in test mode (which is needed for testing purposes only). So, in order to combine both subclasses of `RefactoringOperation` and `NewStartedRefactoringOperation` into uniform `NewStartedRefactoringOperation` we need to store some additional information in order to be able to detect whether a refactoring has to be replayed or not (though, as our experience suggests, we would not be able to replay some refactorings anyway). I look for a way to store this additional information without changing the format of `NewStartedRefactoringOperation`.

**Comment by Wanderer777** [comment]
@reprogrammer: 

The additional information of whether a refactoring should be always replayed (i.e. that this refactoring was an older one) can be serialized/deserialized as part of `refactoringMode` field of `NewStartedRefactoringOperation`. 

Also, considering that this transition from `RefactoringOperation` to `NewStartedRefactoringOperation` happened in the same CodingSpectator version as changing from the old to the new format of other operations (see issue #244), it would be good to incorporate the automatic fix to this issue into the fixer that fixes issue #244 such that the fixer for both issues is executed only once for each older CodingTracker operation sequence.
