### ISSUE TITLE
Store the results of the awareness survey

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#315]
We are going to distribute a survey to understand the awareness of developers about various refactoring tools in Eclipse. I've created a draft of the survey at http://codingspectator.cs.illinois.edu/RefactoringToolsSurvey/. The next step is to store the results in the database and send a notification e-mail when the user submits the form.

**Comment by vazexqi** [comment]
Unfortunately, I think the form has too many things to be filled. I suspect you probably don't want to give them default values since you think it's a good idea to make them read each box properly. But 27 lines x 3 radio boxes = 81 mouse clicks and that will be quite tedious to fill.

How can we make the form simpler? Or how can we make it easier to fill out (maybe bigger checkboxes instead radio boxes?)

**Comment by vazexqi** [comment]
Here's another suggestion: it's quite hard to read each row. So let's alternate the colors.

**Comment by reprogrammer** [comment]
@vazexqi: It's a good idea to alternate the row colors. Do you know how we to do it? I assume we should use a custom CSS style for the table.

**Comment by vazexqi** [comment]
We can follow the stylesheet that I when I created the website for https://netfiles.uiuc.edu/dig/RefactoringInfo/WRT09/

**Comment by reprogrammer** [comment]
I'm closing this issue because we finally decided not to conduct the survey online.
