### ISSUE TITLE
We need to tell the user why we need we are asking for his master password.

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#43]
If the user saves his username/password that we use to upload his Eclipse logs, every time we try to upload the data as the Eclipse starts up, he will be asked to enter his master password for the Eclipse secure storage. However, the generic dialog that asks for the master password doesn't tell the user why it needs the master password. So, the user might just cancel the dialog, because he doesn't know why he has to enter a master password. We have to find a way to communicate to the user why we need his master password.

**Comment by vazexqi** [comment]
It's hard to tell the user why since the master password prompt doesn't provide any facility for telling why it is needed. It's just a very generic master password prompt.

However, we have tried to make it clearer that the master password prompt might be triggered if the user saves the password. This is done by having a better description on the dialog box similar to what Subversive does.

Resolved in d80ccd08f5e65064061d3e654a6676e05f62a95e
