### ISSUE TITLE
There is a potential data race between the JUnit test and the startup event

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#51]
Both the JUnit test and the startup event write into the UUID of the preferences store. If these two activities are performed in two threads, there is a data race in accessing the preference store.

**Comment by vazexqi** [comment]
I have pushed my changes into a separate branch (http://github.com/vazexqi/RefactoringWatcher/commits/submit-log-testing-mode-fix) that you can take a look.

It makes PrefsFacade a thread-safe singleton facade.

It also introduced a testing mode variable so that earlyStartUp doesn't get called when we are running in testing mode. I have exported a JUnit launch configuration to set it up so that the TESTING_MODE environment variable is set.

**Comment by reprogrammer** [comment]
Is there any functional difference between a singleton thread-safe class and of a class whose methods are all static and synchronized?

**Comment by vazexqi** [comment]
Not that I can think of. There might be some slight variations since one is locked by the class object and another is locked by the object itself. But I don't think it will affect us.

**Comment by reprogrammer** [comment]
Resolved by f70703015b30a98e2ff8c61e9bd04514190f9f95.
