### ISSUE TITLE
Look into Mylyn Monitor API to see what we can reuse

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#58]
See http://wiki.eclipse.org/Mylyn_Integrator_Reference#Monitor_API

**Comment by reprogrammer** [comment]
Stas,

Can you take a look at the data that Mylyn captures and compare to those of CodingTracker?

**Comment by Wanderer777** [comment]
The fundamental difference between Mylyn and CodingTracker is that Mylyn looks for interactions of a developer with Eclipse IDE, while CodingTracker looks for interactions of a developer with the underlying Java code. So, all events that CodingTracker captures (except the event that represents Eclipse startup) are related to the code, e.g. editing a file, saving a file, closing an editor window (e.g. without saving the code changes), etc. But unlike Mylyn, CodingTracker is not interested in events that represent selection of a text in an editor, or clicking on a particular button, or changing preferences or perspective. At the same time, there is some overlap, because CodingTracker, for example, listens to window events to detect that an editor is closed or a developer has switched to another editor (i.e. started editing another file).

**Comment by vazexqi** [comment]
Is this issue important? Does it matter anymore if we are/aren't using Mylyn? We have gone pretty far without touching Mylyn so it might not be worthwhile trying to retrofit it now unless there is a good reason (can't think of any at the moment).

Suggestion: close this issue since; it's not a technical issue and is too vague to be an actual issue.

**Comment by reprogrammer** [comment]
@vazexqi: I agree. Therefore, I'm closing this issue.
